### ISSUE TITLE
Fastest Time not Updating

### ISSUE THREAD

**Issue by xnubil** [qalle-fivem/esx-qalle-races#1]
It's comparing the times backwards, and only updating if your time was slower than your last.

Should be:

`if result[1] ~= nil and result[1].time < time then`

https://github.com/qalle-fivem/esx-qalle-races/blob/cd1424076edafff419902c1bd726134b47b25115/server/main.lua#L49

**Comment by qalle-git** [comment]
No? Its checking if result[1].time (your record) > time (new time) If your record is above your new time your new time is lower and that means you did your record and it should update.
